/**
 * Utility to load size variants from pre-analyzed file
 * The analysis should be run once using scripts/analyze-db-sizes.ts
 * This loads from the generated file, not from database
 */

import { readFile } from 'fs/promises';
import { resolve } from 'path';

let cachedSizes: string[] | null = null;

/**
 * Load size variants from pre-analyzed file
 * This should be run once using: tsx web/scripts/analyze-db-sizes.ts
 * 
 * @returns Array of unique size strings from the analysis file
 */
export async function getDbSizeVariants(): Promise<string[]> {
  // Return cached data if available
  if (cachedSizes) {
    return cachedSizes;
  }

  try {
    // Load from analysis file (generated by analyze-db-sizes.ts)
    const analysisPath = resolve(process.cwd(), 'web', 'scripts', 'db-sizes-analysis.json');
    const fileContent = await readFile(analysisPath, 'utf-8');
    const analysis = JSON.parse(fileContent);
    
    if (analysis.allSizes && Array.isArray(analysis.allSizes)) {
      cachedSizes = analysis.allSizes;
      console.log(`📊 Loaded ${cachedSizes.length} size variants from analysis file`);
      return cachedSizes;
    } else {
      console.warn('⚠️ Analysis file exists but allSizes field is missing or invalid');
      return [];
    }
  } catch (fileError: any) {
    // File doesn't exist or is invalid
    if (fileError.code === 'ENOENT') {
      console.warn(
        '⚠️ Size analysis file not found. Please run: tsx web/scripts/analyze-db-sizes.ts'
      );
    } else {
      console.error('❌ Error reading size analysis file:', fileError);
    }
    // Return empty array - sizes extraction will work without DB variants, just less accurate
    return [];
  }
}

/**
 * Clear the cache (useful for testing or after DB updates)
 */
export function clearSizeVariantsCache(): void {
  cachedSizes = null;
  cacheTimestamp = 0;
}
