export const draftSelect = {
  id: true,
  messageId: true,
  from: true,
  fromName: true,
  name: true,
  article: true,
  pricePair: true,
  currency: true,
  material: true,
  description: true,
  gender: true,
  season: true,
  categoryId: true,
  providerId: true,
  source: true,
  status: true,
  isDeleted: true,
  createdAt: true,
  updatedAt: true,
  sizes: true,
  images: {
    select: {
      id: true,
      url: true,
      key: true,
      alt: true,
      sort: true,
      isPrimary: true,
      isActive: true,
      color: true,
      width: true,
      height: true,
    },
  },
  category: {
    select: {
      id: true,
      name: true,
      slug: true,
    },
  },
  provider: {
    select: {
      id: true,
      name: true,
    },
  },
} as const;
